services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Ab@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

  blazortext:
    build:
      context: .
      dockerfile: BlazorText/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./keys:/keys
    networks:
      - appnet
    

networks:
  appnet:
